// generated by stringer -type=CommandStatus; DO NOT EDIT

package shellutil

import "fmt"

const _CommandStatus_name = "OkUnspecifiedErrorProcessKilledCommandNotFoundPipeError"

var _CommandStatus_index = [...]uint8{2, 18, 31, 46, 55}

func (i CommandStatus) String() string {
	if i < 0 || i >= CommandStatus(len(_CommandStatus_index)) {
		return fmt.Sprintf("CommandStatus(%d)", i)
	}
	hi := _CommandStatus_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _CommandStatus_index[i-1]
	}
	return _CommandStatus_name[lo:hi]
}
